In [1]:
from datasets import load_dataset

In [3]:
load_dataset?

Signature:
load_dataset(
    path: str,
    name: Optional[str] = None,
    data_dir: Optional[str] = None,
    data_files: Union[str, collections.abc.Sequence[str], collections.abc.Mapping[str, Union[str, collections.abc.Sequence[str]]], NoneType] = None,
    split: Union[str, datasets.splits.Split, list[str], list[datasets.splits.Split], NoneType] = None,
    cache_dir: Optional[str] = None,
    features: Optional[datasets.features.features.Features] = None,
    download_config: Optional[datasets.download.download_config.DownloadConfig] = None,
    download_mode: Union[datasets.download.download_manager.DownloadMode, str, NoneType] = None,
    verification_mode: Union[datasets.utils.info_utils.VerificationMode, str, NoneType] = None,
    keep_in_memory: Optional[bool] = None,
    save_infos: bool = False,
    revision: Union[datasets.utils.version.Version, str, NoneType] = None,
    token: Union[bool, str, NoneType] = None,
    streaming: bool = False,
    num_proc: Optional[int] = None,
    storage_options: Optional[dict] = None,
    **config_kwargs,
) -> Union[datasets.dataset_dict.DatasetDict, datasets.arrow_dataset.Dataset, datasets.dataset_dict.IterableDatasetDict, datasets.iterable_dataset.IterableDataset]
Docstring:
Load a dataset from the Hugging Face Hub, or a local dataset.

You can find the list of datasets on the [Hub](https://huggingface.co/datasets) or with [`huggingface_hub.list_datasets`].

A dataset is a directory that contains some data files in generic formats (JSON, CSV, Parquet, etc.) and possibly
in a generic structure (Webdataset, ImageFolder, AudioFolder, VideoFolder, etc.)

This function does the following under the hood:

    1. Load a dataset builder:

        * Find the most common data format in the dataset and pick its associated builder (JSON, CSV, Parquet, Webdataset, ImageFolder, AudioFolder, etc.)
        * Find which file goes into which split (e.g. train/test) based on file and directory names or on the YAML configuration
        * It is also possible to specify `data_files` manually, and which dataset builder to use (e.g. "parquet").

    2. Run the dataset builder:

        In the general case:

        * Download the data files from the dataset if they are not already available locally or cached.
        * Process and cache the dataset in typed Arrow tables for caching.

            Arrow table are arbitrarily long, typed tables which can store nested objects and be mapped to numpy/pandas/python generic types.
            They can be directly accessed from disk, loaded in RAM or even streamed over the web.

        In the streaming case:

        * Don't download or cache anything. Instead, the dataset is lazily loaded and will be streamed on-the-fly when iterating on it.

    3. Return a dataset built from the requested splits in `split` (default: all).

Args:

    path (`str`):
        Path or name of the dataset.

        - if `path` is a dataset repository on the HF hub (list all available datasets with [`huggingface_hub.list_datasets`])
          -> load the dataset from supported files in the repository (csv, json, parquet, etc.)
          e.g. `'username/dataset_name'`, a dataset repository on the HF hub containing the data files.

        - if `path` is a local directory
          -> load the dataset from supported files in the directory (csv, json, parquet, etc.)
          e.g. `'./path/to/directory/with/my/csv/data'`.

        - if `path` is the name of a dataset builder and `data_files` or `data_dir` is specified
          (available builders are "json", "csv", "parquet", "arrow", "text", "xml", "webdataset", "imagefolder", "audiofolder", "videofolder")
          -> load the dataset from the files in `data_files` or `data_dir`
          e.g. `'parquet'`.

    name (`str`, *optional*):
        Defining the name of the dataset configuration.
    data_dir (`str`, *optional*):
        Defining the `data_dir` of the dataset configuration. If specified for the generic builders (csv, text etc.) or the Hub datasets and `data_files` is `None`,
        the behavior is equal to passing `os.path.join(data_dir, **)` as `data_files` to reference all the files in a directory.
    data_files (`str` or `Sequence` or `Mapping`, *optional*):
        Path(s) to source data file(s).
    split (`Split` or `str`):
        Which split of the data to load.
        If `None`, will return a `dict` with all splits (typically `datasets.Split.TRAIN` and `datasets.Split.TEST`).
        If given, will return a single Dataset.
        Splits can be combined and specified like in tensorflow-datasets.
    cache_dir (`str`, *optional*):
        Directory to read/write data. Defaults to `"~/.cache/huggingface/datasets"`.
    features (`Features`, *optional*):
        Set the features type to use for this dataset.
    download_config ([`DownloadConfig`], *optional*):
        Specific download configuration parameters.
    download_mode ([`DownloadMode`] or `str`, defaults to `REUSE_DATASET_IF_EXISTS`):
        Download/generate mode.
    verification_mode ([`VerificationMode`] or `str`, defaults to `BASIC_CHECKS`):
        Verification mode determining the checks to run on the downloaded/processed dataset information (checksums/size/splits/...).

        <Added version="2.9.1"/>
    keep_in_memory (`bool`, defaults to `None`):
        Whether to copy the dataset in-memory. If `None`, the dataset
        will not be copied in-memory unless explicitly enabled by setting `datasets.config.IN_MEMORY_MAX_SIZE` to
        nonzero. See more details in the [improve performance](../cache#improve-performance) section.
    revision ([`Version`] or `str`, *optional*):
        Version of the dataset to load.
        As datasets have their own git repository on the Datasets Hub, the default version "main" corresponds to their "main" branch.
        You can specify a different version than the default "main" by using a commit SHA or a git tag of the dataset repository.
    token (`str` or `bool`, *optional*):
        Optional string or boolean to use as Bearer token for remote files on the Datasets Hub.
        If `True`, or not specified, will get token from `"~/.huggingface"`.
    streaming (`bool`, defaults to `False`):
        If set to `True`, don't download the data files. Instead, it streams the data progressively while
        iterating on the dataset. An [`IterableDataset`] or [`IterableDatasetDict`] is returned instead in this case.

        Note that streaming works for datasets that use data formats that support being iterated over like txt, csv, jsonl for example.
        Json files may be downloaded completely. Also streaming from remote zip or gzip files is supported but other compressed formats
        like rar and xz are not yet supported. The tgz format doesn't allow streaming.
    num_proc (`int`, *optional*, defaults to `None`):
        Number of processes when downloading and generating the dataset locally.
        Multiprocessing is disabled by default.

        <Added version="2.7.0"/>
    storage_options (`dict`, *optional*, defaults to `None`):
        **Experimental**. Key/value pairs to be passed on to the dataset file-system backend, if any.

        <Added version="2.11.0"/>
    **config_kwargs (additional keyword arguments):
        Keyword arguments to be passed to the `BuilderConfig`
        and used in the [`DatasetBuilder`].

Returns:
    [`Dataset`] or [`DatasetDict`]:
    - if `split` is not `None`: the dataset requested,
    - if `split` is `None`, a [`~datasets.DatasetDict`] with each split.

    or [`IterableDataset`] or [`IterableDatasetDict`]: if `streaming=True`

    - if `split` is not `None`, the dataset is requested
    - if `split` is `None`, a [`~datasets.streaming.IterableDatasetDict`] with each split.

Example:

Load a dataset from the Hugging Face Hub:

```py
>>> from datasets import load_dataset
>>> ds = load_dataset('cornell-movie-review-data/rotten_tomatoes', split='train')

# Load a subset or dataset configuration (here 'sst2')
>>> from datasets import load_dataset
>>> ds = load_dataset('nyu-mll/glue', 'sst2', split='train')

# Manual mapping of data files to splits
>>> data_files = {'train': 'train.csv', 'test': 'test.csv'}
>>> ds = load_dataset('namespace/your_dataset_name', data_files=data_files)

# Manual selection of a directory to load
>>> ds = load_dataset('namespace/your_dataset_name', data_dir='folder_name')
```

Load a local dataset:

```py
# Load a CSV file
>>> from datasets import load_dataset
>>> ds = load_dataset('csv', data_files='path/to/local/my_dataset.csv')

# Load a JSON file
>>> from datasets import load_dataset
>>> ds = load_dataset('json', data_files='path/to/local/my_dataset.json')
```

Load an [`~datasets.IterableDataset`]:

```py
>>> from datasets import load_dataset
>>> ds = load_dataset('cornell-movie-review-data/rotten_tomatoes', split='train', streaming=True)
```

Load an image dataset with the `ImageFolder` dataset builder:

```py
>>> from datasets import load_dataset
>>> ds = load_dataset('imagefolder', data_dir='/path/to/images', split='train')
```
File:      ~/Documents/ML/Machine-Learning-and-Big-Data-Analytics/venv/lib/python3.12/site-packages/datasets/load.py
Type:      function

Also can use the load_dataset_builder function to load a dataset builder and inspect a dataset's attributes without committing to downloading it:

In [4]:
from datasets import load_dataset_builder

In [5]:
ds_builder = load_dataset_builder("imdb")

In [6]:
ds_builder.info

DatasetInfo(description='', citation='', homepage='', license='', features={'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}, post_processed=None, supervised_keys=None, builder_name='parquet', dataset_name='imdb', config_name='plain_text', version=0.0.0, splits={'train': SplitInfo(name='train', num_bytes=33435948, num_examples=25000, shard_lengths=None, dataset_name='imdb'), 'test': SplitInfo(name='test', num_bytes=32653810, num_examples=25000, shard_lengths=None, dataset_name='imdb'), 'unsupervised': SplitInfo(name='unsupervised', num_bytes=67113044, num_examples=50000, shard_lengths=None, dataset_name='imdb')}, download_checksums={'hf://datasets/imdb@e6281661ce1c48d982bc483cf8a173c1bbeb5d31/plain_text/train-00000-of-00001.parquet': {'num_bytes': 20979968, 'checksum': None}, 'hf://datasets/imdb@e6281661ce1c48d982bc483cf8a173c1bbeb5d31/plain_text/test-00000-of-00001.parquet': {'num_bytes': 20470363, 'checksum': None}, 'hf://datasets/imdb@e6281661ce1c48d982bc483cf8a173c1bbeb5d31/plain_text/unsupervised-00000-of-00001.parquet': {'num_bytes': 41996509, 'checksum': None}}, download_size=83446840, post_processing_size=None, dataset_size=133202802, size_in_bytes=216649642)

In [7]:
ds_builder.info.description

''

In [10]:
ds_builder.info.splits

{'train': SplitInfo(name='train', num_bytes=33435948, num_examples=25000, shard_lengths=None, dataset_name='imdb'),
 'test': SplitInfo(name='test', num_bytes=32653810, num_examples=25000, shard_lengths=None, dataset_name='imdb'),
 'unsupervised': SplitInfo(name='unsupervised', num_bytes=67113044, num_examples=50000, shard_lengths=None, dataset_name='imdb')}

In [8]:
# inspect the dataset features:
ds_builder.info.features

{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}

If happy with the dataset then load it with the load_dataset function...

In [11]:
from datasets import load_dataset

In [12]:
dataset = load_dataset("imdb", split="train")

Splits....

In [14]:
# a split is a specific subset of a dataset like train and test. 
# list a dataset's split names with the get_dataset_split_names function
from datasets import get_dataset_split_names

In [16]:
get_dataset_split_names("imdb")

['train', 'test', 'unsupervised']

Then you can load a specific split with the split parameter. loading a dataset split, returns a dataset object..

In [17]:
from datasets import load_dataset

In [18]:
dataset = load_dataset("imdb", split="train")

In [21]:
dataset

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

Functions exactly like pytorch's 'Dataset' class....

In [22]:
# can be indexed...
dataset[0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.',
 'label': 0}

In [23]:
# has an implemented len
len(dataset)

25000

By not specifying a split, Datasets then returns a DatasetDict object instead...

In [24]:
dataset2 = load_dataset("imdb")

In [25]:
dataset2

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

Configurations:
- some datasets contain configurations and you ought to choose the particular type of config required.  Use the get_dataset_config_names function to retrieve a list of all possible configurations available to your dataset..

In [1]:
from datasets import get_dataset_config_names

In [2]:
configs = get_dataset_config_names("imdb")

In [3]:
print(configs)

['plain_text']

In [4]:
configs = get_dataset_config_names("PolyAI/minds14")
print(configs)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

['all', 'cs-CZ', 'de-DE', 'en-AU', 'en-GB', 'en-US', 'es-ES', 'fr-FR', 'it-IT', 'ko-KR', 'nl-NL', 'pl-PL', 'pt-PT', 'ru-RU', 'zh-CN']

Know your dataset:....

two types of dataset objects.... a regular Dataset and an iterable dataset. A regular dataset provides fast random access to the rows, and memory-mapping so that loading even large datasets only uses a relatively snall amount of device memory. But, fir really, really big datasets that won't even fit on disk or in memory, an iterabledataset allows you to access and use the dataset without waiting for it to download completely.

Dataset....regular dataset:
- when you load a dataset split, you get a dataset object. you can do many things with a dataset object, which is why its important to learn how to manipulate and interact with the data stored inside.

In [6]:
from datasets import load_dataset_builder

In [7]:
ds_builder = load_dataset_builder("cornell-movie-review-data/rotten_tomatoes")

README.md: 0.00B [00:00, ?B/s]

In [8]:
ds_builder.info.description

''

In [9]:
ds_builder.info.splits

{'train': SplitInfo(name='train', num_bytes=1074810, num_examples=8530, shard_lengths=None, dataset_name=None),
 'validation': SplitInfo(name='validation', num_bytes=134679, num_examples=1066, shard_lengths=None, dataset_name=None),
 'test': SplitInfo(name='test', num_bytes=135972, num_examples=1066, shard_lengths=None, dataset_name=None)}

In [10]:
from datasets import load_dataset

In [11]:
dataset = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="train")

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

**Indexing:...**
- indexing to access examples from the dataset just like with pytorch's Dataset class and its indexer.....

In [12]:
dataset[0]

{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .',
 'label': 1}

Indexing by the column name returns a list of all values in the column...

In [13]:
dataset['text']

Column(['the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson\'s expanded vision of j . r . r . tolkien\'s middle-earth .', 'effective but too-tepid biopic', 'if you sometimes like to go to the movies to have fun , wasabi is a good place to start .', "emerges as something rare , an issue movie that's so honest and keenly observed that it doesn't feel like one ."])

In [14]:
len(dataset['text'])

8530

Indexing order doesn't matter... indexing by the column name first returns a column object that can be indexed as usual with row slices.....

In [15]:
import time 

start_time = time.time()
text = dataset[0]['text']
end_time = time.time()
print(f"Elapsed time: {end_time - start_time:.4f} seconds")

Elapsed time: 0.0001 seconds

In [16]:
start_time = time.time()
text = dataset['text'][0]
end_time = time.time()
print(f"Elapsed time: {end_time - start_time:.4f} seconds")

Elapsed time: 0.0005 seconds

Slicing:
- returns a slice of the dataset, which is useful for viewinf several rows at once.

In [17]:
dataset[:3]

{'text': ['the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .',
  'the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson\'s expanded vision of j . r . r . tolkien\'s middle-earth .',
  'effective but too-tepid biopic'],
 'label': [1, 1, 1]}

In [18]:
dataset[3:6]

{'text': ['if you sometimes like to go to the movies to have fun , wasabi is a good place to start .',
  "emerges as something rare , an issue movie that's so honest and keenly observed that it doesn't feel like one .",
  'the film provides some great insight into the neurotic mindset of all comics -- even those who have reached the absolute top of the game .'],
 'label': [1, 1, 1]}

**Iterable Dataset....**
- an iterable dataset is loaded when you set the streaming param to true in load_dataset....

In [19]:
iterable_dataset = load_dataset("ethz/food101", split="train", streaming=True)

README.md: 0.00B [00:00, ?B/s]

In [20]:
for example in iterable_dataset:
    print(example)
    break

{'image': <PIL.Image.Image image mode=RGB size=384x512 at 0x13992D4C0>, 'label': 6}

You can also create an iterable dataset from an existing dataset, but, its faster in streaming mode because the dataset is streamed from local files..

In [21]:
dataset = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="train")
iterable_dataset = dataset.to_iterable_dataset()

An iterable dataset progressively iterates over a dataset one example at a time, you don't have to wait for the whole dataset to download before using it.

an iterable dataset's behavior is different from a regular dataset. you don't get random access to examples in an iterable dataset. Instead, you should iterate over its elements for example, by calling next(iter()) or with a for loop to return the next item from the iterable dataset.

In [22]:
next(iter(iterable_dataset))

{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .',
 'label': 1}

In [23]:
for example in iterable_dataset:
    print(example)
    break

{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'label': 1}

But, an iterable dataset supports column indexing that returns an iterable for the column values

In [24]:
next(iter(iterable_dataset['label']))

1

Creating a subset...
- you can return a subset of the dataset with a specific number of examples in it with IterableDataset.take()

In [25]:
# get the first 3 examples
list(iterable_dataset.take(3))

[{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .',
  'label': 1},
 {'text': 'the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson\'s expanded vision of j . r . r . tolkien\'s middle-earth .',
  'label': 1},
 {'text': 'effective but too-tepid biopic', 'label': 1}]

unlike slicing, iterable_dataset.take(), creates a new iterable dataset...

**Preprocess:**
- In addition to loading datasets, Datasets other main goal is to offer a diverse set of preprocessing functions to get a dataset into an appropriate format for training with an ml framework. 
- Many possible ways to preprocess a dataset - depends on the specific dataset.
- Look at some preprocessing steps here.....

**Tokenize text**
- load the rotten_tomatoes dataset and the tokenizer corresponding to a pretrained BERT model. Using the same tokenizer as a pretrained model - cuz you want to ensure the text is split the same way.

In [1]:
from transformers import AutoTokenizer
from datasets import load_dataset

In [3]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
dataset = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="train")

call the tokenizer on the first row of the dataset...

In [6]:
tokenizer(dataset[0]['text'])

{'input_ids': [101, 1103, 2067, 1110, 17348, 1106, 1129, 1103, 6880, 1432, 112, 188, 1207, 107, 14255, 1389, 107, 1105, 1115, 1119, 112, 188, 1280, 1106, 1294, 170, 24194, 1256, 3407, 1190, 170, 11791, 5253, 188, 1732, 7200, 10947, 12606, 2895, 117, 179, 7766, 118, 172, 15554, 1181, 3498, 6961, 3263, 1137, 188, 1566, 7912, 14516, 6997, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

The tokenizer returns a dictionary with 3 items:
- input_ids: numbers representing the tokens in the text
- token_type_ids: indicates which sequence a token belongs to if there is more than 1 sequence
- attention_mask: indicates whether a token should be masked or not

In [7]:
encodings = tokenizer(dataset[0]['text'])

In [9]:
encodings.input_ids[:10]

[101, 1103, 2067, 1110, 17348, 1106, 1129, 1103, 6880, 1432]

In [13]:
encodings.token_type_ids[:10], max(encodings.token_type_ids)

([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0)

In [22]:
encodings2 = tokenizer("hey there", "my name is Blaise")

In [23]:
encodings2.token_type_ids

[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

as seen from above, main purpose of token type ids is to show where different sequences start and end in the event that more than one sequence is passed to the tokenizer in one go.

fastest way to tokenize the entire dataset is to use the map function. map speeds up tokenization by applying the tokenizer to batches of examples instead of individual examples. Set the batched param to true

In [24]:
def tokenization(example):
    return tokenizer(example['text'])

In [25]:
b_dataset = dataset.map(tokenization, batched=True)

Map:   0%|          | 0/8530 [00:00<?, ? examples/s]

In [28]:
b_dataset

Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 8530
})

setting the format of your dataset to be compatible with your machine learning framework.....
- use the set_format() function to set the dataset format to be compatible with pytorch...

by default, a huggingface dataset stores data in apache arrow format. setting the format returns all numerical columns as tensors. 
- significance of this: seamless dataloader integration (pytorch's dataloader expects tensors, without set_format you'd probably need a custom collate_fn)
- why specify columns.... specify columns to tell the function the columns to return and set to tensors if possible...

In [1]:
b_dataset.set_format(type='torch', columns=['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'])

NameError: name 'b_dataset' is not defined

In [30]:
b_dataset.format['type']

'torch'

the dataset at this point is now ready for training with your ml framework.

**Creating a Dataset:**
- Creating a dataset confers all the advantages of the library to your dataset: fast loading and processing, streaming enormous datasets, memory mapping, and more. 
- In many cases, creating a dataset is as easy as dragging and dropping your data files into a dataset repository on the hub.

**File-based builders:**
- Datasets supports many common formats such as csv, json/jsonl, parquet, txt
- For example, it can read a dataset made up of one or several csv files (in this case pass the csv files as a list):

In [ ]:
from datasets import load_dataset

dataset = load_dataset("csv", data_files="file.csv OR ") # OR PASS A LIST TO DATAFILES

**Folder-based builders:**

**From python dictionaries:...**
- You can also create a dataset from data in python dictionaries. 
- 2 ways you can create data using the from_ methods: The from_generator() method is the most memory-efficient way to create a dataset from a generator due to a generator's iterative behavior. This is especially useful when working with really large datasets that may not fit into memory, since the dataset is generated on disk progressively and then memory mapped....

In [2]:
from datasets import Dataset

In [3]:
def gen():
    yield {"pokemon":"bulbasaur","type":"grass"}
    yield {"pokemon":"squirtle","type":"water"}

In [4]:
ds = Dataset.from_generator(gen)
ds[0]

Generating train split: 0 examples [00:00, ? examples/s]

{'pokemon': 'bulbasaur', 'type': 'grass'}

A generator-based iterabledataset needs to be iterated over with a for loop for example....

In [5]:
from datasets import IterableDataset

In [6]:
ds = IterableDataset.from_generator(gen)
for example in ds:
    print(example)

{'pokemon': 'bulbasaur', 'type': 'grass'}
{'pokemon': 'squirtle', 'type': 'water'}

**Datasets: Processing:**
- hf datasets provides many tools for modifying the structure and content of a dataset. These tools are important for tidying up a dataset, creating additional columns, converting between features and formats, and more...

In [7]:
from datasets import load_dataset

In [8]:
dataset = load_dataset("nyu-mll/glue","mrpc",split="train")

README.md: 0.00B [00:00, ?B/s]

mrpc/train-00000-of-00001.parquet:   0%|          | 0.00/649k [00:00<?, ?B/s]

mrpc/validation-00000-of-00001.parquet:   0%|          | 0.00/75.7k [00:00<?, ?B/s]

mrpc/test-00000-of-00001.parquet:   0%|          | 0.00/308k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

All processing methods in this section return a new Dataset object. Modification is not done in-place.

**Sort, shuffle, select, split, and shard:**

**Sort:**
- Use sort to sort column values according to their numerical values. The provifrd column must be numpy compatible...

In [9]:
dataset['label'][:10]

[1, 0, 1, 0, 1, 1, 0, 1, 0, 0]

In [12]:
dataset['idx'][:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 10]

In [10]:
sorted_dataset = dataset.sort('label')
sorted_dataset['label'][:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [13]:
sorted_dataset['idx'][:10]

[1, 3, 6, 8, 10, 11, 12, 15, 16, 17]

Under the hood - this creates a list of indices that is sorted according to the values of the column. This indices mapping is then used to access the right rows in the underlying arrow table.

**Shuffle:**
- The shuffle func randomly rearranges the column values. can specify the generator parameter in this function to use a different numpy.random_Generator if you want more control over the algorithm used to shuffle the dataset.

In [14]:
shuffled_dataset = sorted_dataset.shuffle(seed=42)
shuffled_dataset['label'][:10]

[1, 1, 1, 0, 1, 1, 1, 1, 1, 0]

shuffling takes the list of indicess [0:len(dataset)] and shuffles it to create an indices mapping. However as soon your dataset has an indices mapping, the speed can become 10x slower. This is because there is an extra step to get the row index to read using the indices mapping. to restore speed, you'd need to reqrite the entire dataset on disk again using Dataset.flatten_indices(), which removes the indices mapping. Alternatively, switch to an IterableDataset

In [15]:
iterable_dataset = dataset.to_iterable_dataset(num_shards=128)
shuffled_iterable_dataset = iterable_dataset.shuffle(seed=42,buffer_size=1000)

Select amd filter:

There's 2 options for filtering rows in a dataset: select() and filter()
- select() returns rows according to a list of indices

In [16]:
small_dataset = dataset.select([0, 10, 20, 30, 40, 50])
len(small_dataset)

6

filter on the other hand, returns rows that matched a specific condition

In [17]:
start_with_ar = dataset.filter(lambda example: example['sentence1'].startswith('Ar'))
len(start_with_ar)

Filter:   0%|          | 0/3668 [00:00<?, ? examples/s]

6

In [18]:
start_with_ar['sentence1']

Column(['Around 0335 GMT , Tab shares were up 19 cents , or 4.4 % , at A $ 4.56 , having earlier set a record high of A $ 4.57 .', 'Arison said Mann may have been one of the pioneers of the world music movement and he had a deep love of Brazilian music .', 'Arts helped coach the youth on an eighth-grade football team at Lombardi Middle School in Green Bay .', 'Around 9 : 00 a.m. EDT ( 1300 GMT ) , the euro was at $ 1.1566 against the dollar , up 0.07 percent on the day .', "Arguing that the case was an isolated example , Canada has threatened a trade backlash if Tokyo 's ban is not justified on scientific grounds ."])

filter can also filter by indices if you set with_indices to True...

In [19]:
even_dataset = dataset.filter(lambda example, idx: idx%2 == 0, with_indices=True)
len(even_dataset)

Filter:   0%|          | 0/3668 [00:00<?, ? examples/s]

1834

In [20]:
len(dataset)/2

1834.0

**Split:**
- The train_test_split function creates train and test splits if the dataset doesn't have them already. This allows for adjusting the relative proportions or an absolute number of samples in each split. In the example below, use the test_size parameter to create a test split that is 10% of the original dataset

In [21]:
dataset.train_test_split(test_size=0.1)

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3301
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 367
    })
})

In [22]:
0.1*len(dataset)

366.8

**Shard:**
- Datasets supports sharding to divide a very large dataset into a predefined number of chunks. Specify the num_shards parameter in shard to determine the number of shards to split the dataset into. You'll also need to provide the shard to return with the index parameter....

In [23]:
from datasets import load_dataset

In [24]:
dataset = load_dataset("stanfordnlp/imdb", split="train")
print(dataset)

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

after sharding the dataset into 4 chunks, the first shard will only have 6250 examples:...

In [25]:
dataset.shard(num_shards=4, index=0)

Dataset({
    features: ['text', 'label'],
    num_rows: 6250
})

In [26]:
len(dataset)/4

6250.0

**Rename, remove, cast, and flatten:**
- The following functions allow you to modify the columns of a dataset.

**Rename:**
- Use rename_column() to rename a column in the dataset. Features associated with the original column are actually moved under the new column name instead of just replacing the original column in place

In [27]:
dataset

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [28]:
dataset = dataset.rename_column('text','sentence')
dataset

Dataset({
    features: ['sentence', 'label'],
    num_rows: 25000
})

**remove:**
- to remove one or more columns, provide the column name to the remove_columns function...

**Cast:**
- Casting types....

In [1]:
from datasets import load_dataset
dataset = load_dataset("nyu-mll/glue", "mrpc", split="train")

In [2]:
dataset.features

{'sentence1': Value('string'),
 'sentence2': Value('string'),
 'label': ClassLabel(names=['not_equivalent', 'equivalent']),
 'idx': Value('int32')}

In [3]:
# the cast function transforms the feature types of one or more columns...
# this function accepts the new features as its argument
from datasets import ClassLabel, Value

In [4]:
new_features = dataset.features.copy()
new_features

{'sentence1': Value('string'),
 'sentence2': Value('string'),
 'label': ClassLabel(names=['not_equivalent', 'equivalent']),
 'idx': Value('int32')}

In [5]:
new_features['label'] = ClassLabel(names=['negative','positive'])
new_features['idx'] = Value('int64')

In [6]:
dataset = dataset.cast(new_features)
dataset.features

Casting the dataset:   0%|          | 0/3668 [00:00<?, ? examples/s]

{'sentence1': Value('string'),
 'sentence2': Value('string'),
 'label': ClassLabel(names=['negative', 'positive']),
 'idx': Value('int64')}

Use cast_column to change the feature type of a single column....

In [7]:
n_dataset = dataset.cast_column('idx', Value('float32'))

Casting the dataset:   0%|          | 0/3668 [00:00<?, ? examples/s]

Flatten:
- sometimes a column can be a nested structure of several types. Take a look at the nested structure below from the squad dataset....

In [8]:
from datasets import load_dataset

In [9]:
dataset = load_dataset("rajpurkar/squad",split='train')
dataset.features

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/14.5M [00:00<?, ?B/s]

plain_text/validation-00000-of-00001.par(…):   0%|          | 0.00/1.82M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/87599 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10570 [00:00<?, ? examples/s]

{'id': Value('string'),
 'title': Value('string'),
 'context': Value('string'),
 'question': Value('string'),
 'answers': {'text': List(Value('string')),
  'answer_start': List(Value('int32'))}}

answers field contains 2 subfields text and answer_start... Use the flatten() function to extract the subfields into their own separate columns......

In [10]:
flat_dataset = dataset.flatten()
flat_dataset

Dataset({
    features: ['id', 'title', 'context', 'question', 'answers.text', 'answers.answer_start'],
    num_rows: 87599
})

**Map:**
- some of the more powerful applications of hf datasets come from the map function. map fn allows to apply a processing function to each example in a dataset, independently or in batches. The fn can even create new rows and columns.....
- Following example, prefix each senetence1 value in the dataset with 'My sentence: '
- Start by creating a function that adds 'My sentence: ' to the beginning of each sentence. the function needs to accept and output a dict:

In [11]:
dataset2 = load_dataset("nyu-mll/glue", "mrpc", split="train")

In [12]:
dataset2.features

{'sentence1': Value('string'),
 'sentence2': Value('string'),
 'label': ClassLabel(names=['not_equivalent', 'equivalent']),
 'idx': Value('int32')}

In [13]:
def add_prefix(example):
    example['sentence1'] = 'My sentence: ' + example['sentence1']
    return example

Use the map function to apply the add_prefix function to the entire dataset...

In [15]:
small_dataset = dataset2.take(100)
updated_dataset = small_dataset.map(add_prefix)

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [16]:
updated_dataset['sentence1'][:5]

['My sentence: Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 "My sentence: Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .",
 'My sentence: They had published an advertisement on the Internet on June 10 , offering the cargo for sale , he added .',
 'My sentence: Around 0335 GMT , Tab shares were up 19 cents , or 4.4 % , at A $ 4.56 , having earlier set a record high of A $ 4.57 .',
 'My sentence: The stock rose $ 2.11 , or about 11 percent , to close Friday at $ 21.51 on the New York Stock Exchange .']

can also remove columns with map.

In [18]:
updated_dataset = small_dataset.map(\
                                    lambda example: {'new_sentence': example['sentence1']},remove_columns=['sentence1'])
updated_dataset.column_names

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

['sentence2', 'label', 'idx', 'new_sentence']

can also use the map with indices if you set with_indices to True. Example below adds the index to the beginning of each sentence...

In [19]:
updated_dataset = small_dataset.map(\
    lambda example, idx : {'sentence2': f'{idx}: '+ example['sentence2']}, with_indices=True
    )
updated_dataset['sentence2'][:5]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

['0: Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 "1: Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .",
 "2: On June 10 , the ship 's owners had published an advertisement on the Internet , offering the explosives for sale .",
 '3: Tab shares jumped 20 cents , or 4.6 % , to set a record closing high at A $ 4.57 .',
 '4: PG & E Corp. shares jumped $ 1.63 or 8 percent to $ 21.03 on the New York Stock Exchange on Friday .']

**Multiprocessing:**
- Multiprocessing significantly speeds up processing by parallelizing processes in the cpu. set the num_proc param in map to set the number of processes to use

In [21]:
updated_dataset = small_dataset.map(\
    lambda example,idx: {'sentence2': f'{idx}: ' +example['sentence2']},\
    with_indices=True,\
    num_proc=4)

Map (num_proc=4):   0%|          | 0/100 [00:00<?, ? examples/s]

num_proc significantly speeds up computations by parallelizing processes in the cpu.

The map function also works with the rank of processes if you set with_rank to True. Analogous to the with_indices param. the with_rank param in the mapped function

**Batch processing:**
- map function supports wotking with batches of examples. Operate on batches by setting batched to true. default batch_size is 1000 but can be adjusted using the batch_size parameter. 
- batch processing enables interesting applications such as splitting long sentences into shorter chunks and data augmentation

**Split long examples:**
- when examples are too long, you may want to split them into several smaller chunks. begin by creating a function that does that

In [22]:
def chunk_examples(examples):
    chunks = []
    for sentence in examples['sentence1']:
        chunks += [sentence[i:i+50] for i in range(0,len(sentence),50)]
    return {"chunks":chunks}

In [24]:
chunked_dataset = dataset2.map(\
    chunk_examples,batched=True,remove_columns=dataset2.column_names\
)

Map:   0%|          | 0/3668 [00:00<?, ? examples/s]

In [25]:
chunked_dataset

Dataset({
    features: ['chunks'],
    num_rows: 10470
})

In [26]:
chunked_dataset[:10]

{'chunks': ['Amrozi accused his brother , whom he called " the ',
  'witness " , of deliberately distorting his evidenc',
  'e .',
  "Yucaipa owned Dominick 's before selling the chain",
  ' to Safeway in 1998 for $ 2.5 billion .',
  'They had published an advertisement on the Interne',
  't on June 10 , offering the cargo for sale , he ad',
  'ded .',
  'Around 0335 GMT , Tab shares were up 19 cents , or',
  ' 4.4 % , at A $ 4.56 , having earlier set a record']}

the data is split into smaller chunks and there's now more rows in the dataset.

**data augmentation:**
- the map function could also be used for data augmentation. the following example generates additional words for a masked token in a sentence.....

the map function can be used for data augmentation. we're gonna test this using the roberta model in transformers' fillmaskpipeline:

In [27]:
from random import randint
from transformers import pipeline

In [28]:
fillmask = pipeline("fill-mask", model="roberta-base")

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use mps:0

In [29]:
mask_token = fillmask.tokenizer.mask_token
smaller_dataset = dataset2.filter(lambda e,i : i<100, with_indices=True)

Filter:   0%|          | 0/3668 [00:00<?, ? examples/s]

Create a function to randomly select a word to mask in the sentence. The function should also return the original sentence and the two top replacements generated by roberta.

In [32]:
def augment_data(examples):
    outputs = []
    for sentence in examples['sentence1']:
        words = sentence.split(' ')
        K = randint(1, len(words)-1)
        masked_sentence = " ".join(words[:K]  + [mask_token] + words[K+1:])
        predictions = fillmask(masked_sentence)
        augmented_sequences = [predictions[i]["sequence"] for i in range(3)]
        outputs += [sentence] + augmented_sequences
    return {"data": outputs}

In [33]:
augmented_dataset = smaller_dataset.map(augment_data, batched=True, remove_columns=smaller_dataset.column_names, batch_size=8)
augmented_dataset[:9]["data"]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

['Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his testimony .',
 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his story .',
 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his statements .',
 "Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .",
 "Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .",
 "Yucaipa owned Dominick 's before selling the company to Safeway in 1998 for $ 2.5 billion .",
 "Yucaipa owned Dominick 's before selling the store to Safeway in 1998 for $ 2.5 billion .",
 'They had published an advertisement on the Internet on June 10 , offering the cargo for sale , he added .']

process multiple splits:
- many datasets have splits that can be processed simultaneously with DatasetDict.map. for example, tokenize the sentence1 field in the train and test split by:

In [34]:
from datasets import load_dataset

In [35]:
# load all the splits.....
dataset3 = load_dataset("nyu-mll/glue","mrpc")
dataset3

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

In [38]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [39]:
encoded_dataset = dataset3.map(lambda examples: tokenizer(examples['sentence1']), batched=True)
encoded_dataset['train'][0]

Map:   0%|          | 0/3668 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0,
 'input_ids': [101,
  7277,
  2180,
  5303,
  4806,
  1117,
  1711,
  117,
  2292,
  1119,
  1270,
  107,
  1103,
  7737,
  107,
  117,
  1104,
  9938,
  4267,
  12223,
  21811,
  1117,
  2554,
  119,
  102],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

Distributed usage:
- when you use map() in a distributed setting, you should also use torch.distributed_barrier. This ensures the main process performs the mapping while the other

**Batch:**
- The batch() method allows you to group samples from the dataset into batches.

In [1]:
from datasets import load_dataset
dataset4 = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="train")

In [2]:
batched_dataset = dataset4.batch(batch_size=4)

Batching examples:   0%|          | 0/8530 [00:00<?, ? examples/s]

In [3]:
batched_dataset[0]

{'text': ['the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .',
  'the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson\'s expanded vision of j . r . r . tolkien\'s middle-earth .',
  'effective but too-tepid biopic',
  'if you sometimes like to go to the movies to have fun , wasabi is a good place to start .'],
 'label': [1, 1, 1, 1]}

**Concatenate:**

In [4]:
from datasets import concatenate_datasets, load_dataset

In [5]:
stories = load_dataset("ajibawa-2023/General-Stories-Collection", split="train")
stories = stories.remove_columns([col for col in stories.column_names if col != "text"])
wiki = load_dataset("wikimedia/wikipedia", "20220301.en", split="train")
wiki = wiki.remove_columns([col for col in wiki.column_names if col != "text"])

README.md:   0%|          | 0.00/606 [00:00<?, ?B/s]

General Stories-0-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-1-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-2-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-3-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-4-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-5-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-6-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-7-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-8-Final.json:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

General Stories-9-Final.json:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

ValueError: BuilderConfig '20220301.en' not found. Available: ['20231101.ab', '20231101.ace', '20231101.ady', '20231101.af', '20231101.als', '20231101.alt', '20231101.am', '20231101.ami', '20231101.an', '20231101.ang', '20231101.anp', '20231101.ar', '20231101.arc', '20231101.ary', '20231101.arz', '20231101.as', '20231101.ast', '20231101.atj', '20231101.av', '20231101.avk', '20231101.awa', '20231101.ay', '20231101.az', '20231101.azb', '20231101.ba', '20231101.ban', '20231101.bar', '20231101.bat-smg', '20231101.bcl', '20231101.be', '20231101.be-x-old', '20231101.bg', '20231101.bh', '20231101.bi', '20231101.bjn', '20231101.blk', '20231101.bm', '20231101.bn', '20231101.bo', '20231101.bpy', '20231101.br', '20231101.bs', '20231101.bug', '20231101.bxr', '20231101.ca', '20231101.cbk-zam', '20231101.cdo', '20231101.ce', '20231101.ceb', '20231101.ch', '20231101.chr', '20231101.chy', '20231101.ckb', '20231101.co', '20231101.cr', '20231101.crh', '20231101.cs', '20231101.csb', '20231101.cu', '20231101.cv', '20231101.cy', '20231101.da', '20231101.dag', '20231101.de', '20231101.din', '20231101.diq', '20231101.dsb', '20231101.dty', '20231101.dv', '20231101.dz', '20231101.ee', '20231101.el', '20231101.eml', '20231101.en', '20231101.eo', '20231101.es', '20231101.et', '20231101.eu', '20231101.ext', '20231101.fa', '20231101.fat', '20231101.ff', '20231101.fi', '20231101.fiu-vro', '20231101.fj', '20231101.fo', '20231101.fon', '20231101.fr', '20231101.frp', '20231101.frr', '20231101.fur', '20231101.fy', '20231101.ga', '20231101.gag', '20231101.gan', '20231101.gcr', '20231101.gd', '20231101.gl', '20231101.glk', '20231101.gn', '20231101.gom', '20231101.gor', '20231101.got', '20231101.gpe', '20231101.gu', '20231101.guc', '20231101.gur', '20231101.guw', '20231101.gv', '20231101.ha', '20231101.hak', '20231101.haw', '20231101.he', '20231101.hi', '20231101.hif', '20231101.hr', '20231101.hsb', '20231101.ht', '20231101.hu', '20231101.hy', '20231101.hyw', '20231101.ia', '20231101.id', '20231101.ie', '20231101.ig', '20231101.ik', '20231101.ilo', '20231101.inh', '20231101.io', '20231101.is', '20231101.it', '20231101.iu', '20231101.ja', '20231101.jam', '20231101.jbo', '20231101.jv', '20231101.ka', '20231101.kaa', '20231101.kab', '20231101.kbd', '20231101.kbp', '20231101.kcg', '20231101.kg', '20231101.ki', '20231101.kk', '20231101.kl', '20231101.km', '20231101.kn', '20231101.ko', '20231101.koi', '20231101.krc', '20231101.ks', '20231101.ksh', '20231101.ku', '20231101.kv', '20231101.kw', '20231101.ky', '20231101.la', '20231101.lad', '20231101.lb', '20231101.lbe', '20231101.lez', '20231101.lfn', '20231101.lg', '20231101.li', '20231101.lij', '20231101.lld', '20231101.lmo', '20231101.ln', '20231101.lo', '20231101.lt', '20231101.ltg', '20231101.lv', '20231101.mad', '20231101.mai', '20231101.map-bms', '20231101.mdf', '20231101.mg', '20231101.mhr', '20231101.mi', '20231101.min', '20231101.mk', '20231101.ml', '20231101.mn', '20231101.mni', '20231101.mnw', '20231101.mr', '20231101.mrj', '20231101.ms', '20231101.mt', '20231101.mwl', '20231101.my', '20231101.myv', '20231101.mzn', '20231101.nah', '20231101.nap', '20231101.nds', '20231101.nds-nl', '20231101.ne', '20231101.new', '20231101.nia', '20231101.nl', '20231101.nn', '20231101.no', '20231101.nov', '20231101.nqo', '20231101.nrm', '20231101.nso', '20231101.nv', '20231101.ny', '20231101.oc', '20231101.olo', '20231101.om', '20231101.or', '20231101.os', '20231101.pa', '20231101.pag', '20231101.pam', '20231101.pap', '20231101.pcd', '20231101.pcm', '20231101.pdc', '20231101.pfl', '20231101.pi', '20231101.pih', '20231101.pl', '20231101.pms', '20231101.pnb', '20231101.pnt', '20231101.ps', '20231101.pt', '20231101.pwn', '20231101.qu', '20231101.rm', '20231101.rmy', '20231101.rn', '20231101.ro', '20231101.roa-rup', '20231101.roa-tara', '20231101.ru', '20231101.rue', '20231101.rw', '20231101.sa', '20231101.sah', '20231101.sat', '20231101.sc', '20231101.scn', '20231101.sco', '20231101.sd', '20231101.se', '20231101.sg', '20231101.sh', '20231101.shi', '20231101.shn', '20231101.si', '20231101.simple', '20231101.sk', '20231101.skr', '20231101.sl', '20231101.sm', '20231101.smn', '20231101.sn', '20231101.so', '20231101.sq', '20231101.sr', '20231101.srn', '20231101.ss', '20231101.st', '20231101.stq', '20231101.su', '20231101.sv', '20231101.sw', '20231101.szl', '20231101.szy', '20231101.ta', '20231101.tay', '20231101.tcy', '20231101.te', '20231101.tet', '20231101.tg', '20231101.th', '20231101.ti', '20231101.tk', '20231101.tl', '20231101.tly', '20231101.tn', '20231101.to', '20231101.tpi', '20231101.tr', '20231101.trv', '20231101.ts', '20231101.tt', '20231101.tum', '20231101.tw', '20231101.ty', '20231101.tyv', '20231101.udm', '20231101.ug', '20231101.uk', '20231101.ur', '20231101.uz', '20231101.ve', '20231101.vec', '20231101.vep', '20231101.vi', '20231101.vls', '20231101.vo', '20231101.wa', '20231101.war', '20231101.wo', '20231101.wuu', '20231101.xal', '20231101.xh', '20231101.xmf', '20231101.yi', '20231101.yo', '20231101.za', '20231101.zea', '20231101.zh', '20231101.zh-classical', '20231101.zh-min-nan', '20231101.zh-yue', '20231101.zu']

Streaming datasets...

In [6]:
from datasets import load_dataset

In [7]:
dataset = load_dataset("HuggingFaceFW/fineweb",split='train',streaming=True)

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/27468 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/27468 [00:00<?, ?it/s]

In [8]:
print(next(iter(dataset)))

{'text': "How AP reported in all formats from tornado-stricken regionsMarch 8, 2012\nWhen the first serious bout of tornadoes of 2012 blew through middle America in the middle of the night, they touched down in places hours from any AP bureau. Our closest video journalist was Chicago-based Robert Ray, who dropped his plans to travel to Georgia for Super Tuesday, booked several flights to the cities closest to the strikes and headed for the airport. He’d decide once there which flight to take.\nHe never got on board a plane. Instead, he ended up driving toward Harrisburg, Ill., where initial reports suggested a town was destroyed. That decision turned out to be a lucky break for the AP. Twice.\nRay was among the first journalists to arrive and he confirmed those reports -- in all formats. He shot powerful video, put victims on the phone with AP Radio and played back sound to an editor who transcribed the interviews and put the material on text wires. He then walked around the devastation with the Central Regional Desk on the line, talking to victims with the phone held so close that editors could transcribe his interviews in real time.\nRay also made a dramatic image of a young girl who found a man’s prosthetic leg in the rubble, propped it up next to her destroyed home and spray-painted an impromptu sign: “Found leg. Seriously.”\nThe following day, he was back on the road and headed for Georgia and a Super Tuesday date with Newt Gingrich’s campaign. The drive would take him through a stretch of the South that forecasters expected would suffer another wave of tornadoes.\nTo prevent running into THAT storm, Ray used his iPhone to monitor Doppler radar, zooming in on extreme cells and using Google maps to direct himself to safe routes. And then the journalist took over again.\n“When weather like that occurs, a reporter must seize the opportunity to get the news out and allow people to see, hear and read the power of nature so that they can take proper shelter,” Ray says.\nSo Ray now started to use his phone to follow the storms. He attached a small GoPro camera to his steering wheel in case a tornado dropped down in front of the car somewhere, and took video of heavy rain and hail with his iPhone. Soon, he spotted a tornado and the chase was on. He followed an unmarked emergency vehicle to Cleveland, Tenn., where he was first on the scene of the storm's aftermath.\nAgain, the tornadoes had struck in locations that were hours from the nearest AP bureau. Damage and debris, as well as a wickedly violent storm that made travel dangerous, slowed our efforts to get to the news. That wasn’t a problem in Tennessee, where our customers were well served by an all-formats report that included this text story.\n“CLEVELAND, Tenn. (AP) _ Fierce wind, hail and rain lashed Tennessee for the second time in three days, and at least 15 people were hospitalized Friday in the Chattanooga area.”\nThe byline? Robert Ray.\nFor being adept with technology, chasing after news as it literally dropped from the sky and setting a standard for all-formats reporting that put the AP ahead on the most competitive news story of the day, Ray wins this week’s $300 Best of the States prize.\n© 2013 The Associated Press. All rights reserved. Terms and conditions apply. See AP.org for details.", 'id': '<urn:uuid:d66bc6fe-8477-4adf-b430-f6a558ccc8ff>', 'dump': 'CC-MAIN-2013-20', 'url': 'http://%20jwashington@ap.org/Content/Press-Release/2012/How-AP-reported-in-all-formats-from-tornado-stricken-regions', 'date': '2013-05-18T05:48:54Z', 'file_path': 's3://commoncrawl/crawl-data/CC-MAIN-2013-20/segments/1368696381249/warc/CC-MAIN-20130516092621-00000-ip-10-60-113-184.ec2.internal.warc.gz', 'language': 'en', 'language_score': 0.9721424579620361, 'token_count': 717}

streaming creates an iterable dataset that is useful for iterative jobs like training a model. Shouldn't use iterable datasets for jobs that require random access to examples because you'd have to iterate all over it using a for loop.

column indexing...
- sometimes its convenient to iterate over values of a specific column. fortunately, an iterable dataset supports column indexing...

In [9]:
dataset = load_dataset("allenai/c4","en",streaming=True,split="train")

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

In [10]:
print(next(iter(dataset["text"])))

Beginners BBQ Class Taking Place in Missoula!
Do you want to get better at making delicious BBQ? You will have the opportunity, put this on your calendar now. Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. He will be teaching a beginner level class for everyone who wants to get better with their culinary skills.
He will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information.
The cost to be in the class is $35 per person, and for spectators it is free. Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.

convert from a dataset....
- an existing dataset can

In [11]:
from datasets import config

In [13]:
config.HF_DATASETS_CACHE

PosixPath('/Users/blaise/.cache/huggingface/datasets')

an existing dataset can be converted to an iterable dataset with the 'to_iterable_dataset' function. This func is actually faster than setting streaming=True, argument in the load_dataset func.

- load_dataset with streaming = True means you're streaming over a network which is slower than streaming over local files
- load_dataset without streaming will download the entire dataset to disk and then by converting it to streaming ensures fast operations since we're streaming on disk
- but the above is the default hf datasets behaviour
- can shard datasets using the to_iterable_dataset fn this ensures u can use multiple workers when using the dataloader
- can perform shuffle operation in an iterable dataset

- can split your iterable dataset in one of 2 ways: take and split... take=> returns the first n examples in a dataset, skip() omits the first n examples in a dataset and returns the remaining ones. 

- shard: datasets support sharding to divide datasets into a predefined number of chunks..
- interleave :

**Use with pytorch:**
- by default datasets return regular python objects: integers, floats, strings, lists, etc. 
- to get pytorch tensors instead, set the format of the dataset to pytorch using Dataset.with_format()

In [14]:
from datasets import Dataset

In [15]:
data = [[1,2],[3,4]]
ds = Dataset.from_dict({"data": data})

In [16]:
ds

Dataset({
    features: ['data'],
    num_rows: 2
})

In [17]:
ds = ds.with_format("torch")

In [18]:
ds[0]

{'data': tensor([1, 2])}

In [19]:
ds[:2]

{'data': tensor([[1, 2],
         [3, 4]])}

to load the data as tensors on a GPU, specify the device argument:

In [20]:
import torch

In [21]:
device = torch.device("mps" if torch.mps.is_available() else "cpu")
ds = ds.with_format("torch", device=device)

In [22]:
ds[0]

{'data': tensor([1, 2])}

In [23]:
device

device(type='mps')

N-dimensional arrays:
- if your dataset consists of N-dimensional arrays....

In [28]:
torch.tensor([[[1, 2],[3, 4]],[[5, 6],[7, 8]]]).shape

torch.Size([2, 2, 2])

In [24]:
data = [[[1, 2],[3, 4]],[[5, 6],[7, 8]]]
ds = Dataset.from_dict({'data': data})

In [25]:
ds = ds.with_format("torch")

In [26]:
ds

Dataset({
    features: ['data'],
    num_rows: 2
})

In [27]:
ds[0]

{'data': tensor([[1, 2],
         [3, 4]])}

In [1]:
from datasets import Dataset

In [2]:
data = [[1,2],[3,4]]
ds = Dataset.from_dict({"data": data})

In [3]:
ds

Dataset({
    features: ['data'],
    num_rows: 2
})

In [4]:
ds[0]

{'data': [1, 2]}

In [5]:
ds[1]

{'data': [3, 4]}

In [7]:
ds = ds.with_format("torch")

In [8]:
ds[0]

{'data': tensor([1, 2])}

In [9]:
ds[:2]

{'data': tensor([[1, 2],
         [3, 4]])}

In [11]:
import torch

In [12]:
device = torch.device("mps" if torch.mps.is_available() else "cpu")

In [13]:
ds = ds.with_format("torch", device=device)

In [14]:
ds[0]

{'data': tensor([1, 2])}

**N-dimensional arrays:**
- if the dataset consists of N-dimensional arrays - by defaault they are considered the same tensor if the shape is fixed.

In [15]:
from datasets import Dataset

In [18]:
z = torch.tensor([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])

In [19]:
z.shape

torch.Size([2, 2, 2])

In [20]:
z[0]

tensor([[1, 2],
        [3, 4]])

In [21]:
z[1]

tensor([[5, 6],
        [7, 8]])

In [16]:
data = [[[1, 2],[3, 4]],[[5, 6],[7, 8]]]

ds = Dataset.from_dict({"data": data})
ds = ds.with_format("torch")

In [17]:
ds[0]

{'data': tensor([[1, 2],
         [3, 4]])}

In [22]:
ds[1]

{'data': tensor([[5, 6],
         [7, 8]])}

In [23]:
# varying shape:
data = [[[1, 2],[3]],[[4, 5, 6],[7, 8]]]
ds = Dataset.from_dict({"data": data})
ds = ds.with_format("torch")

In [24]:
ds[0]

{'data': [tensor([1, 2]), tensor([3])]}

In [25]:
ds[1]

{'data': [tensor([4, 5, 6]), tensor([7, 8])]}

the default conversion logic of hf datasets is often slow and requires shape comparisons and data copies. To avoid this, you must explicitly use the array feature type and specify the shape of your tensors.

In [28]:
from datasets import Dataset, Features, Array2D

In [29]:
data = [[[1, 2],[3, 4]],[[5, 6],[7, 8]]]
features = Features({"data": Array2D(shape=(2,2), dtype='int32')})
ds = Dataset.from_dict({"data": data}, features=features)

In [30]:
ds = ds.with_format("torch")

In [31]:
ds[0]

{'data': tensor([[1, 2],
         [3, 4]])}

In [32]:
ds[:2]

{'data': tensor([[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]])}

other feature types.......
- class label data are properly converted to tensors...

In [33]:
from datasets import Dataset, Features, ClassLabel

In [34]:
labels = [0, 0, 1]
features = Features({"label": ClassLabel(names=['negative','positive'])})
ds = Dataset.from_dict({"label": labels}, features=features)
ds = ds.with_format("torch")

In [35]:
ds[0]

{'label': tensor(0)}

Data loading:
- like torch.utils.data.Dataset objects, a Dataset can be passed directly to a pytorch DataLoader

In [36]:
import numpy as np
from datasets import Dataset
from torch.utils.data import DataLoader

In [37]:
data = np.random.rand(16)
label = np.random.randint(0, 2, size=16)
ds = Dataset.from_dict({"data": data, "label": label}).with_format("torch")
dataloader = DataLoader(ds, batch_size=4)

In [40]:
ds[0]

{'data': tensor(0.3065), 'label': tensor(1)}

In [38]:
for batch in dataloader:
    print(batch)

{'data': tensor([0.3065, 0.9978, 0.7704, 0.6717]), 'label': tensor([1, 0, 0, 1])}
{'data': tensor([0.1221, 0.3130, 0.0620, 0.3731]), 'label': tensor([1, 1, 0, 0])}
{'data': tensor([0.6495, 0.1665, 0.9723, 0.4678]), 'label': tensor([0, 1, 1, 1])}
{'data': tensor([0.4656, 0.0765, 0.7805, 0.1197]), 'label': tensor([1, 1, 1, 1])}

**Optimized data loading:**
- several ways to increase the speed data is loaded. PyTorch offers parallelized data loading, retrieving batches of indices instead of individually, and streaming to iterate over the dataset without downloading it on disk.

**Use multiple workers:**
- You can parallelize data loading with the num_workers argument of a pytorch dataloader and get a higher throughput. Under the hood, the dataloader starts num_worker processes. Each process reloads the dataset passed to the DataLoader and is used to query examples. Reloading the dataset inside a worker doesn't fill up ram, since it simply memory-maps the dataset again from disk

In [41]:
import numpy as np 
from datasets import Dataset, load_from_disk
from torch.utils.data import DataLoader

In [43]:
data = np.random.rand(10_000)
data = Dataset.from_dict({"data": data})

In [46]:
dataloader = DataLoader(data, batch_size=32, num_workers=4)

**Stream Data:**
- stream a dataset by loading it as an iterabledataset. this allows you to progressively iterate over a remote dataset without downloading it on disk and or over local data files.

**Parallel reading with and without shards:**
- num_workers parallelizes reading. Sharding parallelizes where you read from. 
- case 1: no sharding and num_workers > 0
   - one or a few large arrow files, and all workers reading from the same file
   - what happens: workers run in parallel, but they seek into the same file, compete for the same disk bandwidth, and share the same file handles/inode
   - works, but doesn't scale perfectly.
   - bottleneck: disk contention | single-file i/o limits | os read-ahead is less effective
   - multiple people reading different chapters of the same giant book at the same time

- case 2: sharded dataset + num_workers
   - dataset split into many files (shards)
   - each shard contains independent rows
   - each worker reads different shards
   - fewer seeks
   - more sequential reads
   - better disk parallelism

- single file, many workers:
  - disk head thrashes
  - throughput plateaus early

- many shards, many workers
  - near-linear scaling (up to disk limits)
  - much better cache locality

**Checkpoint and resume:**
- if you need a dataloader that you can checkpoint and resume in the middle of training, you can use the stateful dataloader from torchdata

In [47]:
from torchdata.stateful_dataloader import StatefulDataLoader

In [49]:
from datasets import load_dataset

In [50]:
my_iterable_dataset = load_dataset("deepmind/code_contests", streaming=True, split="train")
dataloader = StatefulDataLoader(my_iterable_dataset, batch_size=32, num_workers=4)

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

dataset_infos.json: 0.00B [00:00, ?B/s]

In [51]:
# save in the middle of training
state_dict = dataloader.state_dict()

In [52]:
state_dict

{'_snapshot': {'_snapshot_step': 0,
  '_last_yielded_worker_id': 3,
  '_main_snapshot': {'_num_workers': 4,
   '_sampler_iter_state': {'samples_yielded': 0},
   '_index_sampler_state': None,
   '_sampler_iter_yielded': 0,
   '_IterableDataset_len_called': None,
   '_shared_seed': None,
   '_base_seed': 2373765512381695110},
  '_worker_snapshots': {'worker_0': {'worker_id': 0,
    'dataset_state': {'examples_iterable': {'examples_iterable': {'shard_idx': 0,
       'shard_example_idx': 0,
       'type': 'ArrowExamplesIterable'},
      'previous_state': None,
      'batch_idx': 0,
      'num_chunks_since_previous_state': 0,
      'cropped_chunk_length': 0,
      'type': 'RebatchedArrowExamplesIterable'},
     'epoch': 0},
    'fetcher_state': {'fetcher_ended': False, 'dataset_iter_state': None}},
   'worker_1': {'worker_id': 1,
    'dataset_state': {'examples_iterable': {'examples_iterable': {'shard_idx': 0,
       'shard_example_idx': 0,
       'type': 'ArrowExamplesIterable'},
      'previous_state': None,
      'batch_idx': 0,
      'num_chunks_since_previous_state': 0,
      'cropped_chunk_length': 0,
      'type': 'RebatchedArrowExamplesIterable'},
     'epoch': 0},
    'fetcher_state': {'fetcher_ended': False, 'dataset_iter_state': None}},
   'worker_2': {'worker_id': 2,
    'dataset_state': {'examples_iterable': {'examples_iterable': {'shard_idx': 0,
       'shard_example_idx': 0,
       'type': 'ArrowExamplesIterable'},
      'previous_state': None,
      'batch_idx': 0,
      'num_chunks_since_previous_state': 0,
      'cropped_chunk_length': 0,
      'type': 'RebatchedArrowExamplesIterable'},
     'epoch': 0},
    'fetcher_state': {'fetcher_ended': False, 'dataset_iter_state': None}},
   'worker_3': {'worker_id': 3,
    'dataset_state': {'examples_iterable': {'examples_iterable': {'shard_idx': 0,
       'shard_example_idx': 0,
       'type': 'ArrowExamplesIterable'},
      'previous_state': None,
      'batch_idx': 0,
      'num_chunks_since_previous_state': 0,
      'cropped_chunk_length': 0,
      'type': 'RebatchedArrowExamplesIterable'},
     'epoch': 0},
    'fetcher_state': {'fetcher_ended': False, 'dataset_iter_state': None}}}},
 '_steps_since_snapshot': 0,
 '_iterator_finished': False}

In [53]:
# resume training later
dataloader.load_state_dict(state_dict)

the above is possible because hf datasets implement state dict internally, i.e. state_dict and load_state_dict.

**Distributed:**
-

In [54]:
import os

**Use with pandas:**
- using datasets with pandas - a particular focus on how to process datasets using pandas functions, and how to convert a dataset to pandas or from pandas
- This is particulary useful as it allows fast operations, since datasets uses pyarrow under the hood and pyarrow is well integrated within pandas

**Dataset format:**
- By default, datasets return regular python objects: integers, floats etc. 
- to get pandas dataframes or series instread, set the format to using pandas using the with_format function

In [56]:
from datasets import Dataset

In [57]:
data = {"col_0": ["a", "b", "c", "d"], "col_1": [0., 0., 1., 1.]}
ds = Dataset.from_dict(data)
ds = ds.with_format("pandas")

In [58]:
ds[0]

  col_0  col_1
0     a    0.0

In [59]:
ds[:2]

  col_0  col_1
0     a    0.0
1     b    0.0

**Process data:**
- pandas functions are generally faster than regular hand-written python functions, and are therefore a good option to optimizing data processing. you can use pandas functions to process a dataset in Dataset.map() or Dataset.filter()

In [61]:
from datasets import Dataset

In [62]:
data = {"col_0": ["a", "b", "c", "d"], "col_1": [0., 0., 1., 1.]}
ds = Dataset.from_dict(data)
ds = ds.with_format("pandas")

In [ ]:
ds = ds.map(lambda df: d)

using datasets with apache spark:
- ds = Dataset.from_spark(spark_dataframe)
  - the spark workers write the dataset on disk in a cache directory as arrow files, and the dataset is loaded from there

- Alternatively, you can skip materializing by using IterableDataset.from_spark - which returns an iterable dataset
  - iterable dataset streams rows from spark without materializing them
  - What each actually does:
    - Dataset.from_spark(spark_df) => materialized, disk-backed dataset. 
    - Spark executes the dataframe, data is collected partition-by-partition
    - written to arrow shards on disk
    - exposed as normal hf dataset
    - with dataset you get Spark -> Parquet -> Arrow -> mmap

  - IterableDataset.from_spark => streaming, non-materialized dataset
    - spark executes the dataframe
    - rows are yielded as an iterator
    - nothing written to disk
    - data flows directly to training
  - You get:
     - zero disk usage
     - immediate start
     - can handle datasets larger than disk
 
- Caching:
  - when using Dataset.from_spark() => the resulting Dataset is cached; if you call Dataset.from_spark multiple times on the same dataframe it won't rerun the spark job that writes the datasets as arrow files on disk
  - can set the cache location by passing cache_dir =  to Dataset.from_spark(). 

- HuggingFace files get stored in the huggingface cache at ~/ .cache/huggingface/hub
- cache allows datasets to avoid redownloading if they exist
- datasets also has its own cache to store datasets converted in arrow format
  - default hf datasets cache directory is ~/.cache/huggingface/datasets => change the cache location by setting the shell environment variable, HF_HOME to another directory
    - $export HF_HOME="/path/to/another/directory/datasets"
  - Alternatively, set the HF_DATASETS_CACHE env variable to control only datasets-specific cache dir
    - when you load a dataset, you also have the option to change where the data is cached. Change the cache_dir parameter to the path you want
      - dataset = load_dataset("username/dataset", cache_dir="")
    - download mode:
      - if u need the original dataset without any processing functions applied => re-download the files as shown below:
        - dataset = load_dataset('',download_mode='force_redownload')
      - after downloading a dataset, you can control how it is loaded by load_dataset with download_mode parameter. By default, hf datasets 
- HF Datasets:
  - the hf dataset hub is 
  -